name: BuildAndDeploy

on:
  workflow_dispatch:

jobs:
    
    build:
     runs-on: windows-latest
     env:
      name: "dotnet Build"
      ref-name: ${{github.ref}}
      
     steps:
       - name: checkout-Repo
         uses: actions/checkout@v3.3.0
       - name: Setup .NET Core SDK
         uses: actions/setup-dotnet@v3.0.3
       - name: list
         run: ls
       - name: Create issue if the build is failed
         if: failure()
         run: echo $name
    deployment:
     runs-on: windows-latest
     steps:
      - name: deploy
        uses: ./.github/actions/deploy
      - name: list
        run: ls
