name: BuildAndDeploy

on:
  workflow_dispatch:

jobs:
    
    use-build:
     uses: <owner>/<repo>/First-Contribution/.github/workflows/BuildDeploy.yml@main
    deploy:
     needs: use-build
     runs-on: windows-latest
     steps:
      - name: Download use-build artifact
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v2
        with:
          name: <the name>
          path: <the path>
